Create Rhevm Config Subclass
candlepin/virt-who pull request #105
Opened 2017-10-24 08:30 UTC by jirihnidek

* Created RHEVM config section subclass
* Fixed all unit tests in: test_rhevm.py
* Tested with RHEVM server
* Removed obsolete and unused testing code in __name__ == '__main__'
* Attempt to fix some problems in complex unit tests

2017-10-24 08:33 UTC, jirihnidek commented
![](https://github.trello.services/images/mini-trello-icon.png) [[8] [CONFIG_EPIC] Create Rhevm Config Subclass](https://trello.com/c/NvDfv97y/583-8-configepic-create-rhevm-config-subclass)

2017-10-24 20:03 UTC, cnsnyder requested changes
I believe just a few small changes necessary for complete validation.

Other than the above, looks good.

2017-10-24 20:03 UTC, cnsnyder commented on virtwho/virt/rhevm/rhevm.py
> +
I think the following is necessary to ensure 'server', 'username' and 'password' (or the encrypted variety) is provided:
```
        self.add_key('server', validation_method=self._validate_server, required=True)
        self.add_key('username', validation_method=self._validate_username, required=True)
        self.add_key('password', validation_method=self._validate_unencrypted_password, required=True)
```

2017-10-24 20:10 UTC, cnsnyder requested changes

2017-10-24 20:10 UTC, cnsnyder commented on virtwho/virt/rhevm/rhevm.py
> +            if self.config['hypervisor_id'] == 'uuid':
Should this be in it's own _validate_hypervisor_id method?

2017-10-25 09:48 UTC, jirihnidek commented on virtwho/virt/rhevm/rhevm.py
> -    print dict((host, [guest.toDict() for guest in guests]) for host, guests in rhevm.getHostGuestMapping().items())
@cnsnyder Is it OK to remove this code? I consider it as obsolete.

2017-10-25 16:05 UTC, cnsnyder requested changes
Please update the message from 'warning' to 'error' for the validate_hypervisor_id method (and associated tests)

2017-10-25 16:05 UTC, cnsnyder commented on tests/test_config_section_libvirtd.py
> +            ('warning', 'Invalid option: "unsupported_id" for hypervisor_id, use one of: (uuid, hostname)')
This should be 'error' level as it invalidates the configuration to use an unsupported_id.
The configuration needs a valid hypervisor_id and so it should be considered invalid if a bad one is given.

2017-10-25 19:22 UTC, cnsnyder approved these changes

2017-10-25 19:22 UTC, cnsnyder commented
LGTM! Please squash, and I'll merge!

2017-10-25 19:28 UTC, merged