1387800: [RFE] virt-who can report cluster in host-to-guest mapping
candlepin/virt-who pull request #131
Opened 2018-03-13 15:04 UTC by jirihnidek

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1387800
* Virt-who can report information about cluster, when ESX or
  RHEV is used. It is mostly usefull, when you run virt-who
  with --print parameter. You can get something like this:

    ....
    "facts": {
        "hypervisor.type": "qemu",
        "hypervisor.version": "vdsm-4.19.49-1.el7ev",
        "hypervisor.cluster": "Default", <---- cluster name
        "cpu.cpu_socket(s)": "1"
    }
    ...

* User can easilly see cluster name of hyperviros host
* Updated unit test for ESX and RHEV

2018-03-20 14:19 UTC, wottop commented
Please rebase to master to make the travis tests run correctly.

2018-03-20 15:45 UTC, jirihnidek commented
@wottop Rebased, but one test is failing (all tests are passing on my laptop). I will try to investigate it later.

2018-03-22 08:15 UTC, jirihnidek commented
@wottop restarting unit tests on Travis CI solved the issue. It's ready for review.

2018-03-22 15:52 UTC, cnsnyder requested changes
One minor request:

Could you please update the complex test data for esx and rhevm to include this cluster information?

2018-03-26 19:14 UTC, cnsnyder approved these changes

2018-03-26 19:14 UTC, cnsnyder commented
@jirihnidek Please squash and I'll merge! Looks good!

2018-03-26 19:26 UTC, jirihnidek commented
@cnsnyder squashed

2018-03-28 15:26 UTC, merged