1560598: Pass hostname to M2Crypto in STOMP client
candlepin/virt-who pull request #139
Opened 2018-04-24 20:53 UTC by kahowell

2018-04-27 18:14 UTC, wottop requested changes
How do I test this?

2018-04-27 18:14 UTC, wottop commented on virtwho/virt/vdsm/stomp.py
> +                        self.socket.connect((self.host, int(self.port)))
excess parenthesis?

2018-05-03 19:54 UTC, kahowell commented on virtwho/virt/vdsm/stomp.py
> +                        self.socket.connect((self.host, int(self.port)))
Actually, no. `connect` takes a tuple: see https://docs.python.org/2/library/socket.html

2018-05-03 20:00 UTC, kahowell commented
> How do I test this?

@wottop, you need:
 * a new enough version of RHV to support JSON-RPC over STOMP.
 * ensure that the RHV server has a certificate which uses the hostname (and *not* IP).
 * a version of python that does not support `wrap_socket` (see https://docs.python.org/2/library/ssl.html#ssl.SSLContext.wrap_socket). Looks like a python version older than 2.7.9 *should* work.

It might be easier to fake the python version requirement by tweaking the code to always use M2Crypto...

2018-05-08 17:51 UTC, wottop commented
WIll wait for a vdsm system with the proper certificate setup. Need to see the failure first.

2018-05-23 17:17 UTC, kahowell commented
673e700..53b77e8: rebased against master, added a commit that allows forcing M2Crypto usage via RHSM_USE_M2CRYPTO.

@wottop sending an email w/ testing instructions.

2018-05-23 20:23 UTC, wottop commented
ack

2018-05-23 20:23 UTC, wottop approved these changes

2018-05-23 20:24 UTC, merged