1542652: When the -c option is used, don't parse the default files
candlepin/virt-who pull request #141
Opened 2018-05-02 19:26 UTC by nikosmoum

- Now, when config files are passed through the cli -c option, configurations
in /etc/virt-who.conf and /etc/virt-who.d/* are not parsed.
- 'global' and 'default' sections are not parsed from files passed through
the -c option, but they will still be read from /etc/virt-who.conf.
- 'global' and 'default' sections are not parsed from /etc/virt-who.d/*

2018-05-03 10:23 UTC, jirihnidek requested changes
Overall it's good PR. Please add some "info" message to log file, when -c/--config is used.

2018-05-03 10:23 UTC, jirihnidek commented on virtwho/config.py
> +        all_sections_to_add.update(effective_config.all_drop_dir_config_sections(config_dir=config_dir))
When configuration files from /etc/virt-who.d (it could be also some other directory) are not used, then this information should be printed to log file using `logger.info()` with explanation. I would prefer to print that all files from `config_dir` are ignored.  You can also list all ignored files in the `config_dir`. It's up to you.

2018-05-03 10:23 UTC, jirihnidek commented on virtwho/config.py
> +    # read the file provided to the configs var if defined
The logic is little bit weird, but it's not your fault. Method `init_config` needs refactoring. :smile:

2018-05-03 11:12 UTC, nikosmoum commented on virtwho/config.py
> +        all_sections_to_add.update(effective_config.all_drop_dir_config_sections(config_dir=config_dir))
logging added

2018-05-04 07:39 UTC, jirihnidek approved these changes
ACK

2018-05-04 07:39 UTC, merged