1510920: Change the choreography for the job status check
candlepin/virt-who pull request #156
Opened 2018-06-27 17:40 UTC by wottop

The order has been changed so that the status is not checked directly
 after the submission. The current method was resulting in multiple
 status check retries while the checkin was being processed.

This version will check immediately before the next run. If the previous
 job has not yet been processed, it will be bypassed until the next interval

One shot reports will no longer wait for the status to be returned.

2018-07-10 08:49 UTC, jirihnidek requested changes
Overall, it is good PR. I only request some small changes.

2018-07-10 08:49 UTC, jirihnidek commented on virtwho/manager/subscriptionmanager/subscriptionmanager.py
> +    def cancel_job(self, report):
This function isn't used.

2018-07-10 08:49 UTC, jirihnidek commented on virtwho/virt/virt.py
> +from rhsm.connection import RestlibException
It seems that imported class `RestlibException` is not used.

2018-07-10 08:49 UTC, jirihnidek commented on virtwho/virt/virt.py
> +            first_attempt = False
Nitpick: there should be two empty lines between two classes.

2018-07-10 08:49 UTC, jirihnidek commented on virtwho/virt/virt.py
> +    def check_report_status(self, report):
Please add some doc string for this method.

2018-07-10 08:49 UTC, jirihnidek commented on virt-who.spec
> +Requires:       subscription-manager-rhsm >= 1.21.6
BTW: Why is required this version?

2018-07-12 13:35 UTC, wottop commented on virtwho/manager/subscriptionmanager/subscriptionmanager.py
> +    def cancel_job(self, report):
it was an earlier idea where the job would get canceled if not finished. I had left it in in case we ever need to make that cancel happen.

2018-07-12 13:37 UTC, wottop commented on virt-who.spec
> +Requires:       subscription-manager-rhsm >= 1.21.6
See above comment on cancel_job.  This is the version that has the cancel_job call in it.

2018-07-13 11:52 UTC, jirihnidek approved these changes
ACK

2018-07-13 11:52 UTC, merged