1577954: Added config option filter_type; ENT-580
candlepin/virt-who pull request #165
Opened 2018-08-13 13:35 UTC by jirihnidek

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1577954
* Added new config file option filter_type. Value of this option
  can be one of: 'wildcards, 'regex'.
* When filtering is used and filter_type is not specified, then
  warning is printed to log file. Behavior should be the same.

2018-08-15 20:09 UTC, wottop requested changes

2018-08-15 20:09 UTC, wottop commented on tests/test_config_section_virt.py
>      def test_validate_filter_hypervisor_id_hostname(self):
Is there a test for a regex and no filter type set?
I'd like to see a test of this fall back.

2018-08-16 13:18 UTC, jirihnidek commented on tests/test_config_section_virt.py
>      def test_validate_filter_hypervisor_id_hostname(self):
@wottop This fallback is covered by existing unit tests in `test_virt.py'. I added more tests there and I also updated manual page of `virt-who-config.5`.

2018-08-17 17:23 UTC, wottop commented
go ahead and squash. ack otherwise.

2018-08-22 11:37 UTC, jirihnidek commented
@wottop commits are squashed

2018-08-23 12:14 UTC, wottop commented
ack

2018-08-23 12:14 UTC, merged