1369634: Dont log proxy html errors for hyperv: (ENT-613)
candlepin/virt-who pull request #176
Opened 2018-09-07 14:57 UTC by nikosmoum

- When hyperv gets an HTML page as error response from a proxy, don't log the whole html, but try to scrape the title off of it.
- If scraping the title doesn't work, only log the http error code.

2018-09-10 08:25 UTC, jirihnidek requested changes
Overall it is good PR. Please do small refactoring of code to avoid future problems.

2018-09-10 08:25 UTC, jirihnidek commented on virtwho/virt/hyperv/hyperv.py
> +                    title = xml.find('.//title')
I know that you are using existing variable and it's not your fault, but please do small refactoring here and rename `xml` to something like `xml_doc`, because `xml` is well known Python module (`ElementTree` is imported from this module). It could cause some issues in the future.

2018-09-10 12:38 UTC, nikosmoum commented
@jirihnidek fixed all variables in this file called `xml`

2018-09-11 07:39 UTC, jirihnidek approved these changes
ACK

2018-09-11 07:39 UTC, merged