1530290: Remove enviroment as an input variable for the hypervisor ch…
candlepin/virt-who pull request #213
Opened 2019-05-20 13:34 UTC by wottop

…eck in

The current server is not using this value so there is little need to send it

2019-05-22 14:08 UTC, jirihnidek requested changes
Thanks for PR. Overall It is good PR. I think it is necessary to remove `env` from man pages `virt-who-config.5`. BTW: there are also some obsolete CLI arguments in virt-who.zsh.

2019-05-22 14:08 UTC, jirihnidek commented on tests/test_config_section_libvirtd.py
>          assert 'server' in self.virt_config
I would remove this method, because it doesn't test almost anything.

2019-05-22 14:08 UTC, jirihnidek commented on tests/test_fake.py
> -env=covfefe
:-)

2019-05-23 13:51 UTC, wottop commented
Will squash after second revue

2019-05-23 14:43 UTC, jirihnidek approved these changes
ACK. Please squash and then it is ready to be merged to master.

2019-05-23 14:50 UTC, wottop commented
squashed

2019-05-24 08:49 UTC, merged