1530254: Update checking on environment variables
candlepin/virt-who pull request #230
Opened 2019-08-01 13:21 UTC by wottop

This check was written before the error handling of configurations was normalized.
It is now redundant and causes entry processing to be short-circuited.

2019-08-02 12:43 UTC, jirihnidek requested changes
Hi Will,
overall it is good solution. I would only add following unit test to `test/test_config_section_virt.py`:

```python
    def test_validate_missing_owner(self):
        """
        Test validation of missing type of virtualization backend
        """
        self.init_virt_config_section()
        del self.virt_config['owner']
        result = self.virt_config.validate()
        self.assertIn(('error', 'Required option: "owner" not set.'), result)
        self.assertEqual(len(result), 1)
```

Thoughts?

2019-08-02 12:50 UTC, jirihnidek commented
> I would only add following unit test to `test/test_config_section_virt.py`:

Well, this unit test is passing in master too. It has to be somewhere else and something little bit different...

2019-08-02 18:02 UTC, wottop commented
That error exists in the previous version also. I am eliminating the error check when the ENV values are put in the config. This test doesn't show a difference.

2019-08-05 07:42 UTC, jirihnidek approved these changes
ACK

2019-08-05 07:42 UTC, merged