1762780: fix bug, when reporter_id is empty; ENT-1706
candlepin/virt-who pull request #247
Opened 2020-01-10 20:36 UTC by jirihnidek

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1762780
* Validation using _validate_non_empty_string did not have side
  effect of setting default value and debug print also didn't
  print default value

2020-01-10 20:37 UTC, jirihnidek commented
It needs more testing, because I changed validation method.

2020-01-13 14:39 UTC, wottop requested changes

2020-01-13 14:39 UTC, wottop commented on virtwho/config.py
> +                    result = ('warning', '%s is not set to a valid string and has default value: %s' % key)
has *no* default value?

2020-01-14 10:22 UTC, jirihnidek commented on virtwho/config.py
> +                    result = ('warning', '%s is not set to a valid string and has default value: %s' % key)
Good point. Thanks.

2020-01-14 15:34 UTC, wottop commented
ack

2020-01-14 15:34 UTC, merged