1658440: Remove the use of environment variables for configuration
candlepin/virt-who pull request #279
Opened 2020-11-04 18:55 UTC by wottop

2020-11-05 16:09 UTC, cnsnyder commented on virtwho/migrate/migrateconfiguration.py
> +Abstraction for accessing different subscription managers.
We should update this description to describe the migrateconfiguration module.

2020-11-05 16:09 UTC, cnsnyder commented on virtwho/migrate/migrateconfiguration.py
> +Copyright (C) 2014 Radek Novacek <rnovacek@redhat.com>
We should update the copyright as well

2020-11-05 20:44 UTC, wottop commented
As this is the first commit to be exclusively RHEL9, I have removed the execution of the tests in python 2.7.

2020-11-09 17:14 UTC, jirihnidek requested changes
Overall, I like this PR :+1: , but I have several requests, some questions and some comments :smiley:

2020-11-09 17:14 UTC, jirihnidek commented on .travis.yml
> -  - "2.7"
:+1:

2020-11-09 17:14 UTC, jirihnidek commented on tests/test_config_migrate.py
> +from __future__ import print_function
Is this really necessary now? Is there any chance that we will run this using Python2?

2020-11-09 17:14 UTC, jirihnidek commented on tests/test_config_migrate.py
> +import shutil
I would move this line to other imports.

2020-11-09 17:14 UTC, jirihnidek commented on tests/test_config_migrate.py
> +            os.makedirs(self.tmp_config_dir)
Not totally against using `/tmp/configtest` , but I would use `tempfile.TemporaryDirectory`. More details here: https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory

2020-11-09 17:14 UTC, jirihnidek commented on tests/test_config_migrate.py
> +        with open(os.path.join(self.tmp_config_dir, "virt-who"), "w") as f:
I would create two variables for `os.path.join(self.tmp_config_dir, "virt-who")` and `os.path.join(self.tmp_config_dir, "virt-who.conf")` in `setUp`, because it is used in many tests and to code will be easier to read.

2020-11-09 17:14 UTC, jirihnidek commented on tests/test_config_migrate.py
> +
Please add here one more empty line.

2020-11-09 17:14 UTC, jirihnidek commented on tests/test_config_migrate.py
> +        self.assertEqual(("").join(result), expected_conf)
Could be simplified:
```python
self.assertEqual("".join(result), expected_conf)
```

2020-11-09 17:14 UTC, jirihnidek commented on virt-who.spec
> +%{python_exec} %{python_sitelib}/virtwho/migrate/migrateconfiguration.py
Shouldn't be here conditions like this?:

```spec
%if (0%{?fedora} > 33 || 0%{?rhel} > 8)
%{python_exec} %{python_sitelib}/virtwho/migrate/migrateconfiguration.py
%endif
```

Or will you solve it by cherry-picking to some release branch?

2020-11-09 17:14 UTC, jirihnidek commented on virt-who-config.5
> +Optional proxy password for the Subscription Asset Manager or Satellite 6 server to use in place of the no proxy filter defined in the system's rhsm.conf.
I guess that small mistake is here. I think that this text would be correct: "Optional proxy settings for the ..."

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/__init__.py
> +__all__ = []
No empty line at the end of the file.

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/__init__.py
> +from __future__ import absolute_import, print_function
I don't think that this is necessary anymore.

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/migrateconfiguration.py
> +
Too many empty lines.

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/migrateconfiguration.py
> +                output.append('\n')
Why adding empty line, when length of output is higher than 0 ?

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/migrateconfiguration.py
> +                output.append('\n')
Why adding empty line, when length of output is higher than 0 ? Better visual experience of generated file? I cannot understand to that.

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/migrateconfiguration.py
> +    Lines = []
Please convert `Lines` to `lines`. It looks like a class.

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/migrateconfiguration.py
> +        interval = os.environment['VIRTWHO_INTERVAL']
I guess it should be `os.environ['VIRTWHO_INTERVAL']`

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/migrateconfiguration.py
> +
In general I would use for getting environment variables (`interval`, `debug` and `one_shot`) something like this:
```python
interval = os.environ.get('VIRTWHO_INTERVAL', None)
```

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/migrateconfiguration.py
> +    if env_vars.get('VIRTWHO_INTERVAL'):
I would use: `if 'VIRTWHO_INTERVAL' in env_vars`:

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/migrate/migrateconfiguration.py
> +        interval = env_vars.pop('VIRTWHO_INTERVAL')
You use `pop` here, because you want to save `interval` in `[global]` section and the other env. vars. will be saved in `[system_environment]` section, right? If so, then please add some explanation comment.

2020-11-09 17:14 UTC, jirihnidek commented on virtwho/parser.py
> -                               help="[Deprecated] Password for connecting to PC")
Nice remove :+1: :smile:

2020-11-10 19:34 UTC, wottop commented on virtwho/migrate/migrateconfiguration.py
> +                output.append('\n')
It's to put a space before the new section. Just visual.

2020-11-10 19:34 UTC, wottop commented on virtwho/migrate/migrateconfiguration.py
> +                output.append('\n')
Same as above

2020-11-13 12:42 UTC, jirihnidek commented on virtwho/migrate/migrateconfiguration.py
> +                output.append('\n')
OK :-)

2020-11-13 12:43 UTC, jirihnidek approved these changes
ACK

2020-11-13 12:43 UTC, merged