Fix virt-who for AHV
candlepin/virt-who pull request #376
Opened 2022-05-30 13:31 UTC by need349

We're using Redhat Satellite 6.10.5 with Nutanix AHV as described in article https://access.redhat.com/articles/6216971?band=se&seSessionId=db907cbb-dfa3-42f7-b16e-37d302f8c0f3&seSource=Recommendation&seResourceOriginID=e786357f-c4a6-4aaf-bc74-8c78a8380821 with an instance of Nutanix Prism Central for reporting the host/guest-mapping with virt-who.
It seems, that virt-who always reports the same VM's as the filter with the Nutanix REST API v3 seems not get applied.

Virt-Who Version: 1.30.12-1.el8 (via RHEL Repositorys)
OS: Red Hat Enterprise Linux 8

Since the last update of virt-who, we had problems, that virt-who just reports a small part of vms and not all.
I've put a little bit of research and some cups of coffee in it and found out, that the function make_rest_call in ahv_interface.py doesn't applies the filter length and offset correctly. So virt-who always asks the Prism Central API for the first 20 vms over and over again without any body for filtering. I hope, that it's understandable with the screen attachemend and the empty json body ({}). The problem seems to be also in the latest version of virt-who, so I'm running the pull request on 1.31.22.

I've fixed that by adjusting the ahv_interface.py. Also I've increased the length of the request chunks from 20 to 100 (max length from nutanix api is 500), to improve the virt-who performance a little bit. Otherwise a run with virt-who is with 1800 vms on nutanix is extremely slow and takes over 30 minutes per run.

This is the very first pull request on this project, so if you miss anything, just let me know!

![grafik](https://user-images.githubusercontent.com/75493523/171000143-55ef1ad4-0604-4344-9c86-45051e38e1c3.png)

2022-06-03 15:30 UTC, jirihnidek requested changes
Thanks for the PR. Overall it looks OK, but I have to test it more, because currently I have access to hypervisor only with one guest and I'm not admin of this machine.

I have small requests in comments of the code ATM.

Can you please add at least one unit test for this case? If you don't know how to add it, then it is OK and we can add unit tests later.

2022-06-03 15:30 UTC, jirihnidek commented on virtwho/virt/ahv/ahv_interface.py
> +        length = 100
Could you please add constants 100 as a class attribute (something like `NUM_OF_REQUESTED_VMS`) ?

2022-06-03 15:30 UTC, jirihnidek commented on virtwho/virt/ahv/ahv_interface.py
>          offset = 0
Could you please rename this variable to something like `initial_offset`?

2022-06-07 11:01 UTC, jirihnidek requested changes
I verified that proposed change works as expected. I have more requests.

2022-06-07 11:01 UTC, jirihnidek commented on virtwho/virt/ahv/ahv_interface.py
> +        res = self.make_rest_call(method=cmd_method, uri=url, json=body)
It doesn't make sense to set body, when version prism v2 REST API is used. It does not make sense to set body for GET method

https://www.nutanix.dev/api_references/prism-v2-0/#/b3A6MjU1ODkwNzk-get-a-list-of-virtual-machines

2022-06-07 11:01 UTC, jirihnidek commented on virtwho/virt/ahv/ahv_interface.py
> +            'length': length
I would set `offset` (equal to 0) here too due to consistency.

2022-06-13 16:05 UTC, need349 commented
Thanks for the review! I've just fixed the comments, just let me know if I miss anything.
I'm also working on a unit test for this case, just give me some days to work that out..

2022-06-29 10:13 UTC, jirihnidek requested changes
Hi, thanks for updates, but your changes made it worse. Your changes cause failures. You can see it, when you e.g. run unit tests. You can run unit tests using `py.test` command.

2022-06-29 10:13 UTC, jirihnidek commented on virtwho/virt/ahv/ahv_interface.py
> -        length = 0
You cannot do that, because `length` does not exists on line 545 and it causes failures.

2022-06-29 10:13 UTC, jirihnidek commented on virtwho/virt/ahv/ahv_interface.py
> -        offset = 0
I suggested to rename this variable to `initial_offset` not removing it. This removal is causing failures at line 555.

2022-06-29 10:14 UTC, jirihnidek commented
BTW: commits should be squashed into one commit in this case.

2022-06-29 10:42 UTC, jirihnidek commented
The code also fails with following traceback during testing `./virt-who -d -o -c /path/to/nutanix.conf` and nothing is reported to candlepin server (I use setup with only two VMs):

```
2022-06-29 12:39:23,958 [virtwho.main ERROR] MainProcess(72411):Thread-2 @virt.py:run:527 - Thread 'nutanix_conf' fails with exception:
Traceback (most recent call last):
  File "/home/jhnidek/githup/candlepin/virt-who/virtwho/virt/virt.py", line 518, in run
    self._run()
  File "/home/jhnidek/githup/candlepin/virt-who/virtwho/virt/ahv/ahv.py", line 195, in _run
    assoc = self.getHostGuestMapping()
  File "/home/jhnidek/githup/candlepin/virt-who/virtwho/virt/ahv/ahv.py", line 116, in getHostGuestMapping
    host_uvm_map = self._interface.build_host_to_uvm_map(self.version)
  File "/home/jhnidek/githup/candlepin/virt-who/virtwho/virt/ahv/ahv_interface.py", line 776, in build_host_to_uvm_map
    vm_uuids = self.get_vms_uuid(version)
  File "/home/jhnidek/githup/candlepin/virt-who/virtwho/virt/ahv/ahv_interface.py", line 555, in get_vms_uuid
    'offset': offset
NameError: name 'offset' is not defined
```

2022-07-06 13:51 UTC, need349 commented
Sorry, unfortunately I missed, that the variable is used for a lot of other stuff. I fixed that and ran multiple tests with Prism Central and Prism Elements and the report works as expected. If I miss something, just let me know!

2022-07-13 13:29 UTC, wottop commented
There is a stylish error:

./virtwho/virt/ahv/ahv_constants.py:27:2: W292 no newline at end of file

1     W292 no newline at end of file

2022-08-26 09:35 UTC, jirihnidek commented
Closing this PR, because #377 (containing code provided in this PR) was merged to main. Thanks again for your contribution.

2022-08-26 09:35 UTC, closed without merging