Begin use of EffectiveConfig Sections in creation of virt backends
candlepin/virt-who pull request #87
Opened 2017-07-20 21:44 UTC by cnsnyder

This PR finishes laying the ground work for using the new ConfigSections to create virt backends.

Please note: As there are no backend specific ConfigSections yet (especially including any that handle encrypted password bits) there are a number of tests which do not pass and will not pass.

I fully expect all tests to pass when the config_refactor branch is merged to master but for this step I think it's necessary for them not to (in order to keep the PRs at least somewhat small).

For testing purposes I expect the libvirt backend to work as expected in all forms of configuration. I've added a temporary commit to modify the libvirt backend to work with a generic config section. Encrypted passwords will still not work with the libvirt backend.

2017-07-20 21:45 UTC, cnsnyder commented
![](https://github.trello.services/images/mini-trello-icon.png) [[8] [CONFIG_EPIC] Create/revise Factory class](https://trello.com/c/hJ3P6WHB/474-8-configepic-create-revise-factory-class)

2017-07-21 14:12 UTC, jirihnidek requested changes
I think that it is on good way. I have some suggestions.

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
>          """
Doc string should be updated: `@rtype: (set, set, dict, set)`

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
> +        return sorted([(key, self[key]) for key in self])
Method `items` should be iterator to be compatible with Python3 and to bee little bit more memory effective.

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
> +            all_sections.update(parse_file(os.path.join(config_dir, conf), parser=parser))
The default parses is ` StripQuotesConfigParser` so the `parses=parser` could be omitted here.

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
>          non_conf_files = None
Initialization of `all_dir_content', 'conf_files' and `non_conf_files` is useless.

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
> +    def validation_messages_as_string(self):
It is not used at any place and any unit test doesn't exist for this method either.

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
> +    def is_section_default(self):
The name of method could be more self-descriptive or please add doc string.

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
> +            sections = parser._sections
Is it really necessary to use `parses._sections`? I think it is possible to use `parses.sections()` and `parser.remove_section()` at line 708.

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
> +
This looks like familiar to me ;-).

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
> +                    effective_config)
I hope this new code could be in some function.

2017-07-21 14:12 UTC, jirihnidek commented on virtwho/config.py
> +    _effective_config = None
BTW: I would modify `EffectiveConfig` to be singleton. Using `global` is not my favorite approach. ;-)

2017-07-24 18:15 UTC, cnsnyder commented on virtwho/config.py
> +                    effective_config)
I'm not sure I understand? What is the request here?

2017-07-24 18:16 UTC, cnsnyder commented on virtwho/config.py
> +
;-)

2017-07-24 21:21 UTC, cnsnyder commented
I have made the EffectiveConfig class a singleton through the use of a metaclass (/me cringes at the thought). Spent quite a bit of time playing with different options for accomplishing this and it seems this works the best for our use case. (Also updated to address the other comments).

Worth mentioning, in our case (thanks to pickle) we can still end up with different instances of the EffectiveConfig.

I look forward to hearing your thoughts.

Cheers!

2017-07-25 06:58 UTC, jirihnidek requested changes
I have only one comment containing answer to your question. Overall your other changes are good. 👍

2017-07-25 06:58 UTC, jirihnidek commented on virtwho/config.py
> +                    effective_config)
I'm sorry. I meant the block of code between lines 1231-1252 could be refactored into some function (e.g. named `check_valid_conf()`). It is not good practice to have long functions (due to worse readability, etc.). The function `init_config()` is quite long now and it is not worthwhile to make it longer :-).

2017-07-25 15:49 UTC, jirihnidek approved these changes
Ack :-)

2017-07-25 16:38 UTC, merged