1466015: Warn of deprecation of command line options in next release
candlepin/virt-who pull request #90
Opened 2017-08-04 18:46 UTC by wottop

2017-08-07 12:26 UTC, wottop commented
![](https://github.trello.services/images/mini-trello-icon.png) [1466015 - [RFE] Add warning that we will remove backend CLI configuration options in a future release](https://trello.com/c/jQwPIGeK/514-ions)

2017-08-17 21:17 UTC, cnsnyder requested changes
Please see the comments above. A few more options need to be listed as deprecated.

Thank you!

2017-08-17 21:17 UTC, cnsnyder commented on virt-who-config.5
> -The id of this virt-who instance, reported with all mappings.
These options will still be allowable in the configuration files.
The man pages changes necessary are in ./virt-who.8

Please update that man page accordingly.

Thank you!!

2017-08-17 21:17 UTC, cnsnyder commented on virtwho/parser.py
> +            print("The option --%s is deprecated and will be removed in the next release." % option)
I would add something to the effect of "please see 'man virt-who-config' for details on adding a configuration section"

2017-08-17 21:17 UTC, cnsnyder commented on virtwho/parser.py
>      virt_group = parser.add_argument_group(
All options in the virt_group as well as satellite_group will be deprecated. (as we are moving to configuration file only).

2017-08-24 19:16 UTC, cnsnyder approved these changes
Nevermind, there are still options that need to be listed as deprecated.

All options that allow command line configuration of virt backends are to be deprecated.
Any that match the below (glob-like) expression:
```--*-{username,env,owner,server,password}```
Should be deprecated.

2017-08-24 19:26 UTC, cnsnyder requested changes
Nevermind, there are still options that need to be listed as deprecated.

All options that allow command line configuration of virt backends are to be deprecated.
Any that match the below (glob-like) expression:
```--*-{username,env,owner,server,password}```
Should be deprecated.

2017-08-28 18:04 UTC, cnsnyder requested changes
Please update this to include all deprecated options per prior changes. Thank you.

2017-08-28 18:04 UTC, cnsnyder commented on virtwho/parser.py
> +    DEPRECATED_OPTIONS = ['log_per_config', 'log_dir', 'log_file', 'reporter_id',
Please update this to include all deprecated options above.

2017-09-06 14:55 UTC, cnsnyder commented on virtwho/parser.py
> +                          'satellite-server', 'satellite-username', 'satellite-password']
I think we'll need to add 'libvirt', 'vdsm', 'esx', 'xen', 'rhevm', 'hyperv'.

2017-09-06 17:38 UTC, cnsnyder approved these changes
LGTM!

Thank you for the contribution!

2017-09-06 17:56 UTC, cnsnyder requested changes
Tests do not pass.
It is because of the extra 'i' on line 327 (it appears).

After the removal of this there is one failing test, which does not fail in master.

It appears the failure is due to one of the DEPRECATED_OPTIONS not being in the  cli_options dict. I think this is because the options end up in that dict with all '-' changed to '_'.

Sorry for the back and forth...

Cheers

2017-09-25 18:53 UTC, cnsnyder approved these changes
Looks good to me. Merging!

2017-09-25 18:53 UTC, merged